---
- hosts: localhost
  vars:
   #   ansible_python_interpreter: "/usr/bin/python3"
      api_key: "{{ lookup('env','API_HETZNER') }}"
  collections:
    - hetzner.hcloud
  tasks:
    - name: Multiple environmentâ€‹ variables in a single line ansible task
      debug:
        msg: "{{ api_key }}"
    - name: hetzner info
      hetzner.hcloud.hcloud_datacenter_info:
        api_token: "{{ api_key }}"
    - name: Gather hcloud datacenter info
      hcloud_datacenter_info:
        api_token: "{{ api_key }}"
      register: output
    - name: Print the gathered info
      debug:
        var: output
